services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0 #7.17.16
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0 #7.17.16
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200    # address of elasticsearch docker container which kibana will connect
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  
  # eland:
  #   image: docker.elastic.co/eland/eland:8.12.0 #7.17.16
  #   command: ["eland_import_hub_model","--url","http://elasticsearch:9200","--hub-model-id","sentence-transformers/clip-ViT-B-32-multilingual-v1","--task-type","text_embedding","--start"]
  #   depends_on:
  #     - elasticsearch                                          # kibana will start when elasticsearch has started

volumes:
  elasticsearch-data:
  